BACKUP_IGNORE_HEAD:
- __p
- .
BACKUP_IGNORE_KEY:
- logfile
- logfile_bk
# - baselines
- expert_data
BACKUP_IGNORE_TAIL:
- .tar
BASE_PATH: null
# LOG_DIR_BACKING_NAME: refer_log0613
LOG_FOLDER_NAME: logfile
LOG_FOLDER_NAME_BK: logfile_bk
# MAIN_MACHINE_IP:
# - 172.16.15.99
# MAIN_MACHINE_LOG_PATH: /mnt/FREENAS/ai/Logging/refer_log0613
# MAIN_MACHINE_PASSWD: luofanming
# MAIN_MACHINE_PORT:
# - 22
# MAIN_MACHINE_USER: luofanming
# WORKSPACE_PATH: /home/luofm/Data
