obj: maxentirl_sa
env_name: Humanoid-v2
information: maxent_irl
alg_name: ppo_transfer
seed: 333
cuda: -1
env:
  env_name: NonStHumanoid-v0
  T: 1000
  state_indices: all
  action_dependent: false
  rand_param: ['gravity']
sac:
  epochs: 10000
  log_step_interval: 5000
  update_every: 50
  update_num: 1
  random_explore_episodes: 10
  batch_size: 100
  lr: 1e-3
  alpha: 0.2
  automatic_alpha_tuning: false
  buffer_size: 1000000
  num_test_episodes: 10
expert:
  samples_episode: 64

reward: # from irl model
  state_only: false
  use_bn: false
  residual: false
  hid_act: relu
  hidden_sizes: [64, 64]
  clamp_magnitude: 10
  gail_reward: false
